import { Component, inject, OnInit } from '@angular/core';
import { RouterModule, RouterOutlet } from '@angular/router';
import TimeAgo from 'javascript-time-ago';
import en from 'javascript-time-ago/locale/en.json';
import { HttpClient } from '@angular/common/http';
import { routeAnimations } from './app.routes';
import { ShellComponent } from '@garudalinux/core';
import { MenuItem } from 'primeng/api';
import { NgOptimizedImage, registerLocaleData } from '@angular/common';
import { ScrollTop } from 'primeng/scrolltop';
import { APP_CONFIG } from '../environments/app-config.token';
import { EnvironmentModel } from '../environments/environment.model';
import localeEnGb from '@angular/common/locales/en-GB';
import { FooterComponent } from './footer/footer.component';
import { Meta } from '@angular/platform-browser';

@Component({
  imports: [RouterModule, ShellComponent, NgOptimizedImage, ScrollTop, FooterComponent],
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
  animations: [routeAnimations],
})
export class AppComponent implements OnInit {
  title = 'Chaotic-AUR';

  private readonly appConfig: EnvironmentModel = inject(APP_CONFIG);
  private readonly httpClient = inject(HttpClient);
  private readonly meta = inject(Meta);

  items: MenuItem[] = [
    {
      icon: 'pi pi-home',
      label: 'Home',
      routerLink: '/',
    },
    {
      icon: 'pi pi-book',
      label: 'Get started',
      routerLink: '/docs',
    },
    {
      icon: 'pi pi-gauge',
      label: 'Build status',
      routerLink: '/status',
    },
    {
      icon: 'pi pi-receipt',
      label: 'Deploy log',
      routerLink: '/deploy-log',
    },
    {
      icon: 'pi pi-table',
      label: 'Package list',
      routerLink: '/package-list',
    },
    {
      icon: 'pi pi-chart-bar',
      label: 'Statistics',
      routerLink: '/stats',
    },
    {
      icon: 'pi pi-cloud-download',
      label: 'Mirrors',
      routerLink: '/mirrors',
    },
    {
      icon: 'pi pi-trophy',
      label: 'Memorial v2',
      routerLink: '/memorial-v2',
    },
    {
      icon: 'pi pi-user',
      label: 'About us',
      routerLink: '/about',
    },
  ];

  ngOnInit() {
    TimeAgo.addDefaultLocale(en);
    registerLocaleData(localeEnGb);

    this.updateMetaTags();

    // Cause stat metrics to be pre-generated by calling its URL,
    // which are then cached in the backend for 5 minutes
    const routesToPreCache = [
      '30d/users',
      '30d/packages',
      '30d/rank/30/packages',
      '30d/rank/30/countries',
      '30d/user-agents',
    ];
    for (const route of routesToPreCache) {
      this.httpClient.get(this.appConfig.cachedMetricsUrl + route);
    }
  }

  /**
   * Returns the animation state of the next page for page transitions
   * @param outlet Router outlet element
   * @returns The animation state of the target route
   */
  prepareRoute(outlet: RouterOutlet): string {
    return outlet.activatedRouteData['animationState'];
  }

  private updateMetaTags() {
    this.meta.addTag({ name: 'description', content: "Building packages for you, so you don't have to!" });
    this.meta.addTag({ name: 'keywords', content: 'Chaotic-AUR, AUR, repository, Archlinux' });
    this.meta.addTag({ property: 'og:title', content: 'Chaotic-AUR - automated binary repo 👨🏻‍💻' });
    this.meta.addTag({ property: 'og:description', content: "Building packages for you, so you don't have to!" });
    this.meta.addTag({ property: 'og:image', content: '/assets/logo.webp' });
    this.meta.addTag({ property: 'og:site_name', content: 'Chaotic-AUR' });
    this.meta.addTag({ property: 'og:url', content: 'https://aur.chaotic.cx' });
  }
}
