import { NgOptimizedImage, registerLocaleData } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import localeEnGb from '@angular/common/locales/en-GB';
import { ChangeDetectionStrategy, Component, inject, OnInit } from '@angular/core';
import { Meta } from '@angular/platform-browser';
import { RouterModule, RouterOutlet } from '@angular/router';
import { MessageToastService, ShellComponent } from '@garudalinux/core';
import TimeAgo from 'javascript-time-ago';
import en from 'javascript-time-ago/locale/en.json';
import { MenuItem } from 'primeng/api';
import { APP_CONFIG } from '../environments/app-config.token';
import { EnvironmentModel } from '../environments/environment.model';
import { routeAnimations } from './app.routes';
import { FooterComponent } from './footer/footer.component';
import { AppService } from './app.service';
import { BuildStatus, ChaoticEvent } from '@./shared-lib';
import { LoadingService } from './loading/loading.service';
import { ProgressSpinner } from 'primeng/progressspinner';

@Component({
  imports: [
    RouterModule,
    ShellComponent,
    NgOptimizedImage,
    FooterComponent,
    ProgressSpinner,
    ProgressSpinner,
    ProgressSpinner,
  ],
  selector: 'chaotic-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
  animations: [routeAnimations],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent implements OnInit {
  private readonly appConfig: EnvironmentModel = inject(APP_CONFIG);
  private readonly appService = inject(AppService);
  private readonly httpClient = inject(HttpClient);
  private readonly messageToastService = inject(MessageToastService);
  private readonly meta = inject(Meta);

  protected readonly loadingService = inject(LoadingService);

  items: MenuItem[] = [
    {
      icon: 'pi pi-home',
      label: 'Home',
      routerLink: '/',
    },
    {
      icon: 'pi pi-book',
      label: 'Get started',
      routerLink: '/docs',
    },
    {
      icon: 'pi pi-gauge',
      label: 'Build status',
      routerLink: '/status',
    },
    {
      icon: 'pi pi-receipt',
      label: 'Deployments',
      routerLink: '/deployments',
    },
    {
      icon: 'pi pi-table',
      label: 'Packages',
      routerLink: '/packages',
    },
    {
      icon: 'pi pi-chart-bar',
      label: 'Statistics',
      routerLink: '/stats',
    },
    {
      icon: 'pi pi-cloud-download',
      label: 'Mirrors',
      routerLink: '/mirrors',
    },
    {
      icon: 'pi pi-trophy',
      label: 'Memorial',
      routerLink: '/memorial-v2',
    },
    {
      icon: 'pi pi-user',
      label: 'About us',
      routerLink: '/about',
    },
  ];

  ngOnInit() {
    TimeAgo.addDefaultLocale(en);
    registerLocaleData(localeEnGb);

    this.updateMetaTags();

    // Cause stat metrics to be pre-generated by calling its URL,
    // which are then cached in the backend for 5 minutes
    const routesToPreCache = ['30d/users', '30d/rank/30/countries', '30d/user-agents'];
    for (const route of routesToPreCache) {
      this.httpClient.get(`${this.appConfig.cachedMetricsUrl}/${route}`).subscribe();
    }

    this.appService.serverEvents.onmessage = ({ data }) => {
      const event = JSON.parse(data) as ChaoticEvent;
      if (event.type === 'build' && event.status === BuildStatus.SUCCESS) {
        this.messageToastService.success(
          'Package deployment',
          `${event.package}-${event.version}-${event.pkgrel} has just been deployed to ${event.repo} 🚀`,
        );
      }

      this.appService.chaoticSse$.next(event);
    };
  }

  /**
   * Returns the animation state of the next page for page transitions
   * @param outlet Router outlet element
   * @returns The animation state of the target route
   */
  prepareRoute(outlet: RouterOutlet): string {
    return outlet.activatedRouteData['animationState'];
  }

  private updateMetaTags() {
    this.meta.addTag({ name: 'description', content: "Building packages for you, so you don't have to!" });
    this.meta.addTag({ name: 'keywords', content: 'Chaotic-AUR, AUR, repository, Archlinux' });
    this.meta.addTag({ property: 'og:title', content: 'Chaotic-AUR - automated binary repo 👨🏻‍💻' });
    this.meta.addTag({ property: 'og:description', content: "Building packages for you, so you don't have to!" });
    this.meta.addTag({ property: 'og:image', content: '/assets/logo.png' });
    this.meta.addTag({ property: 'og:site_name', content: 'Chaotic-AUR' });
    this.meta.addTag({ property: 'og:url', content: 'https://aur.chaotic.cx' });
  }
}
