name: chaotic-next
services:
  chaotic_db:
    build: ./docker/postgres-hll
    container_name: chaotic_db
    restart: always
    network_mode: host
    shm_size: 128mb
    environment:
      POSTGRES_DB: chaotic
      POSTGRES_PASSWORD: chaotic
      POSTGRES_USER: chaotic
    volumes:
      - chaotic_dev:/var/lib/postgresql/18/docker
volumes:
  chaotic_dev:
    external: true
    name: chaotic-next_chaotic_dev
