packages:
  - libs
allowBuilds:
  '@parcel/watcher': false
  '@scarf/scarf': false
  '@swc/core': true
  bcrypt: true
  esbuild: true
  less: false
  lmdb: false
  msgpackr-extract: true
  nx: true
  sharp: false
  unrs-resolver: true
  workerd: true
