name = "caur-frontend"
pages_build_output_dir = "dist/frontend/browser"
compatibility_date = "2024-06-03"

[placement]
mode = "off"

[vars]
NODE_VERSION = "23.2"

[env.production]
compatibility_date = "2024-09-02"

[env.production.placement]
mode = "smart"

[env.production.vars]
NODE_VERSION = "23.2.0"
