import { z } from 'zod';

export const envValidationSchema = z.looseObject({
  AUTH_COOKIE_DOMAIN: z.string().min(1).optional(),
  BETTER_AUTH_TRUSTED_ORIGINS: z.string().optional(),
  BETTER_AUTH_URL: z.url().optional(),
  CAUR_BUILDER_CLAMAV_IMAGE: z.string().min(1).optional(),
  CAUR_BUILDER_CPU_LIMIT: z.string().regex(/^\d+$/).optional(),
  CAUR_BUILDER_DOCKER_SOCKET: z.string().min(1).optional(),
  CAUR_BUILDER_EXTRA_PACMAN_KEYRINGS: z.string().min(1).optional(),
  CAUR_BUILDER_EXTRA_PACMAN_REPOS: z.string().min(1).optional(),
  CAUR_BUILDER_IDLE_TIMEOUT: z.string().regex(/^\d+$/).optional(),
  CAUR_BUILDER_IMAGE: z.string().min(1).optional(),
  CAUR_BUILDER_PIDS_LIMIT: z.string().regex(/^\d+$/).optional(),
  CAUR_BUILDER_POLL_INTERVAL: z.string().regex(/^\d+$/).optional(),
  CAUR_BUILDER_PUBLIC_URL: z.url().optional(),
  CAUR_BUILDER_RAM_LIMIT: z.string().regex(/^\d+$/).optional(),
  CAUR_BUILDER_TIMEOUT: z.string().regex(/^\d+$/).optional(),
  CAUR_BUILDER_WORKDIR: z.string().min(1).optional(),
  CAUR_PORT: z.string().regex(/^\d+$/).optional(),
  CAUR_TRUST_PROXY: z.string().min(1).optional(),
  GITLAB_REDIRECT_URI: z.url().optional(),
  HTTP_LOGGING: z.enum(['true', 'false']).optional(),
  LOG_LEVEL: z.enum(['fatal', 'error', 'warn', 'info', 'debug', 'trace']).optional(),
  OBSERVE_APP_KEY: z.string().min(1).optional(),
  OBSERVE_APP_SECRET: z.string().min(1).optional(),
  OBSERVE_SERVICE_ID: z.string().min(1).optional(),
  PG_POOL_MAX: z.string().regex(/^\d+$/).optional(),
  PG_POOL_MIN: z.string().regex(/^\d+$/).optional(),
  PG_PORT: z.string().regex(/^\d+$/).optional(),
  REDIS_PORT: z.string().regex(/^\d+$/).optional(),
  REPOMANAGER_ABI_DRY_RUN: z.enum(['true', 'false']).optional(),
  REPOMANAGER_REGEN_DB: z.enum(['true', 'false']).optional(),
  REPOMANAGER_SIGNAL_SCAN_ENABLED: z.enum(['true', 'false']).optional(),
});
