/**
 * Real-world Arch provider ELF analyses captured from the live production
 * database after the no-SONAME rescan fix. Used as import fixtures so the
 * e2e suite exercises recompute-broken and dependency-graph logic against
 * genuine soname data (e.g. tcl/tk no-SONAME basenames, grpc ABI bumps).
 */

export interface RealPkgSeed {
  pkgname: string;
  version: string;
  providedSonames: string[];
  neededSonames: string[];
}

export const REAL_ARCH_PROVIDERS: RealPkgSeed[] = [
  {
    pkgname: 'boost-libs',
    version: '1.91.0',
    providedSonames: [
      'libboost_atomic.so.1.91.0',
      'libboost_charconv.so.1.91.0',
      'libboost_chrono.so.1.91.0',
      'libboost_cobalt.so.1.91.0',
      'libboost_cobalt_io.so.1.91.0',
      'libboost_cobalt_io_ssl.so.1.91.0',
      'libboost_container.so.1.91.0',
      'libboost_context.so.1.91.0',
      'libboost_contract.so.1.91.0',
      'libboost_coroutine.so.1.91.0',
      'libboost_date_time.so.1.91.0',
      'libboost_fiber.so.1.91.0',
      'libboost_filesystem.so.1.91.0',
      'libboost_graph.so.1.91.0',
      'libboost_graph_parallel.so.1.91.0',
      'libboost_iostreams.so.1.91.0',
      'libboost_json.so.1.91.0',
      'libboost_locale.so.1.91.0',
      'libboost_log.so.1.91.0',
      'libboost_log_setup.so.1.91.0',
      'libboost_math_c99.so.1.91.0',
      'libboost_math_c99f.so.1.91.0',
      'libboost_math_c99l.so.1.91.0',
      'libboost_math_tr1.so.1.91.0',
      'libboost_math_tr1f.so.1.91.0',
      'libboost_math_tr1l.so.1.91.0',
      'libboost_mpi.so.1.91.0',
      'libboost_mpi_python314.so.1.91.0',
      'libboost_nowide.so.1.91.0',
      'libboost_numpy314.so.1.91.0',
      'libboost_prg_exec_monitor.so.1.91.0',
      'libboost_process.so.1.91.0',
      'libboost_program_options.so.1.91.0',
      'libboost_python314.so.1.91.0',
      'libboost_random.so.1.91.0',
      'libboost_regex.so.1.91.0',
      'libboost_serialization.so.1.91.0',
      'libboost_stacktrace_addr2line.so.1.91.0',
      'libboost_stacktrace_basic.so.1.91.0',
      'libboost_stacktrace_from_exception.so.1.91.0',
      'libboost_stacktrace_noop.so.1.91.0',
      'libboost_thread.so.1.91.0',
      'libboost_timer.so.1.91.0',
      'libboost_type_erasure.so.1.91.0',
      'libboost_unit_test_framework.so.1.91.0',
      'libboost_url.so.1.91.0',
      'libboost_wave.so.1.91.0',
      'libboost_wserialization.so.1.91.0',
      'mpi.so',
    ],
    neededSonames: [
      'ld-linux-x86-64.so.2',
      'libboost_atomic.so.1.91.0',
      'libboost_charconv.so.1.91.0',
      'libboost_chrono.so.1.91.0',
      'libboost_cobalt.so.1.91.0',
      'libboost_cobalt_io.so.1.91.0',
      'libboost_container.so.1.91.0',
      'libboost_context.so.1.91.0',
      'libboost_date_time.so.1.91.0',
      'libboost_filesystem.so.1.91.0',
      'libboost_graph.so.1.91.0',
      'libboost_log.so.1.91.0',
      'libboost_mpi.so.1.91.0',
      'libboost_mpi_python314.so.1.91.0',
      'libboost_python314.so.1.91.0',
      'libboost_random.so.1.91.0',
      'libboost_regex.so.1.91.0',
      'libboost_serialization.so.1.91.0',
      'libboost_thread.so.1.91.0',
      'libbz2.so.1.0',
      'libc.so.6',
      'libcrypto.so.3',
      'libgcc_s.so.1',
      'libicudata.so.78',
      'libicui18n.so.78',
      'libicuuc.so.78',
      'liblzma.so.5',
      'libm.so.6',
      'libmpi.so.40',
      'libpython3.14.so.1.0',
      'libssl.so.3',
      'libstdc++.so.6',
      'libz.so.1',
      'libzstd.so.1',
    ],
  },
  {
    pkgname: 'gdal',
    version: '3.13.2',
    providedSonames: ['libgdal.so.39'],
    neededSonames: [
      'ld-linux-x86-64.so.2',
      'libImath-3_2.so.30',
      'libOpenEXR-3_4.so.33',
      'libaec.so.0',
      'libarchive.so.13',
      'libarrow.so.2400',
      'libarrow_compute.so.2400',
      'libarrow_dataset.so.2400',
      'libblosc.so.1',
      'libc.so.6',
      'libcfitsio.so.10',
      'libcrypto.so.3',
      'libcryptopp.so.8',
      'libcurl.so.4',
      'libdeflate.so.0',
      'libexpat.so.1',
      'libfreexl.so.1',
      'libgcc_s.so.1',
      'libgdal.so.39',
      'libgeos_c.so.1',
      'libgeotiff.so.5',
      'libgif.so.7',
      'libgomp.so.1',
      'libhdf5.so.320',
      'libheif.so.1',
      'libjpeg.so.8',
      'libjson-c.so.5',
      'libjxl.so.0.12',
      'libjxl_threads.so.0.12',
      'liblz4.so.1',
      'liblzma.so.5',
      'libm.so.6',
      'libmariadb.so.3',
      'libmuparser.so.2',
      'libnetcdf.so.22',
      'libodbc.so.2',
      'libodbcinst.so.2',
      'libopenjp2.so.7',
      'libparquet.so.2400',
      'libpcre2-8.so.0',
      'libpng16.so.16',
      'libpodofo.so.2',
      'libpoppler.so.162',
      'libpq.so.5',
      'libproj.so.25',
      'libqhull_r.so.8.0',
      'libspatialite.so.8',
      'libsqlite3.so.0',
      'libstdc++.so.6',
      'libtiff.so.6',
      'libwebp.so.7',
      'libxerces-c-3.3.so',
      'libxml2.so.16',
      'libz.so.1',
      'libzstd.so.1',
    ],
  },
  {
    pkgname: 'glib2',
    version: '2.88.3',
    providedSonames: [
      'libgio-2.0.so.0',
      'libgirepository-2.0.so.0',
      'libglib-2.0.so.0',
      'libgmodule-2.0.so.0',
      'libgobject-2.0.so.0',
      'libgthread-2.0.so.0',
    ],
    neededSonames: [
      'libc.so.6',
      'libffi.so.8',
      'libgio-2.0.so.0',
      'libgirepository-2.0.so.0',
      'libglib-2.0.so.0',
      'libgmodule-2.0.so.0',
      'libgobject-2.0.so.0',
      'libm.so.6',
      'libmount.so.1',
      'libpcre2-8.so.0',
      'libz.so.1',
    ],
  },
  {
    pkgname: 'grpc',
    version: '1.83.0',
    providedSonames: [
      'libaddress_sorting.so.56',
      'libgpr.so.56',
      'libgrpc++.so.1.83',
      'libgrpc++_alts.so.1.83',
      'libgrpc++_error_details.so.1.83',
      'libgrpc++_reflection.so.1.83',
      'libgrpc++_unsecure.so.1.83',
      'libgrpc.so.56',
      'libgrpc_authorization_provider.so.1.83',
      'libgrpc_plugin_support.so.1.83',
      'libgrpc_unsecure.so.56',
      'libgrpcpp_channelz.so.1.83',
      'libupb_base_lib.so.56',
      'libupb_descriptor_lib.so.56',
      'libupb_hash_lib.so.56',
      'libupb_json_lib.so.56',
      'libupb_lex_lib.so.56',
      'libupb_mem_lib.so.56',
      'libupb_message_lib.so.56',
      'libupb_mini_descriptor_lib.so.56',
      'libupb_mini_table_lib.so.56',
      'libupb_reflection_lib.so.56',
      'libupb_textformat_lib.so.56',
      'libupb_wire_lib.so.56',
      'libutf8_range_lib.so.56',
    ],
    neededSonames: [
      'ld-linux-x86-64.so.2',
      'libabsl_cord.so.2605.0.0',
      'libabsl_cordz_functions.so.2605.0.0',
      'libabsl_cordz_info.so.2605.0.0',
      'libabsl_flags_internal.so.2605.0.0',
      'libabsl_flags_marshalling.so.2605.0.0',
      'libabsl_flags_reflection.so.2605.0.0',
      'libabsl_hash.so.2605.0.0',
      'libabsl_kernel_timeout_internal.so.2605.0.0',
      'libabsl_log_globals.so.2605.0.0',
      'libabsl_log_internal_check_op.so.2605.0.0',
      'libabsl_log_internal_conditions.so.2605.0.0',
      'libabsl_log_internal_message.so.2605.0.0',
      'libabsl_log_internal_nullguard.so.2605.0.0',
      'libabsl_random_internal_entropy_pool.so.2605.0.0',
      'libabsl_random_internal_randen.so.2605.0.0',
      'libabsl_random_internal_randen_hwaes_impl.so.2605.0.0',
      'libabsl_random_internal_randen_slow.so.2605.0.0',
      'libabsl_raw_hash_set.so.2605.0.0',
      'libabsl_spinlock_wait.so.2605.0.0',
      'libabsl_status.so.2605.0.0',
      'libabsl_statusor.so.2605.0.0',
      'libabsl_str_format_internal.so.2605.0.0',
      'libabsl_strings.so.2605.0.0',
      'libabsl_synchronization.so.2605.0.0',
      'libabsl_throw_delegate.so.2605.0.0',
      'libabsl_time.so.2605.0.0',
      'libabsl_time_zone.so.2605.0.0',
      'libabsl_vlog_config_internal.so.2605.0.0',
      'libaddress_sorting.so.56',
      'libc.so.6',
      'libcares.so.2',
      'libcrypto.so.3',
      'libgcc_s.so.1',
      'libgpr.so.56',
      'libgrpc++.so.1.83',
      'libgrpc.so.56',
      'libgrpc_plugin_support.so.1.83',
      'libgrpc_unsecure.so.56',
      'libm.so.6',
      'libprotobuf.so.35.1.0',
      'libprotoc.so.35.1.0',
      'libre2.so.11',
      'libssl.so.3',
      'libstdc++.so.6',
      'libsystemd.so.0',
      'libupb_base_lib.so.56',
      'libupb_descriptor_lib.so.56',
      'libupb_hash_lib.so.56',
      'libupb_json_lib.so.56',
      'libupb_lex_lib.so.56',
      'libupb_mem_lib.so.56',
      'libupb_message_lib.so.56',
      'libupb_mini_descriptor_lib.so.56',
      'libupb_mini_table_lib.so.56',
      'libupb_reflection_lib.so.56',
      'libupb_textformat_lib.so.56',
      'libupb_wire_lib.so.56',
      'libutf8_range.so.35.1.0',
      'libutf8_range_lib.so.56',
      'libutf8_validity.so.35.1.0',
      'libz.so.1',
    ],
  },
  {
    pkgname: 'lmdb',
    version: '0.9.35',
    providedSonames: ['liblmdb.so'],
    neededSonames: ['libc.so.6'],
  },
  {
    pkgname: 'lua',
    version: '5.5.1',
    providedSonames: ['liblua++.so.5.5', 'liblua.so.5.5'],
    neededSonames: ['libc.so.6', 'libgcc_s.so.1', 'libm.so.6', 'libstdc++.so.6'],
  },
  {
    pkgname: 'lua51-lpeg',
    version: '1.1.0',
    providedSonames: ['lpeg.so'],
    neededSonames: ['libc.so.6'],
  },
  {
    pkgname: 'ghc-libs',
    version: '9.6.6',
    providedSonames: [
      'libHSCabal-3.10.3.0-ghc9.6.6.so',
      'libHSCabal-syntax-3.10.3.0-ghc9.6.6.so',
      'libHSarray-0.5.6.0-ghc9.6.6.so',
      'libHSbase-4.18.2.1-ghc9.6.6.so',
      'libHSbinary-0.8.9.1-ghc9.6.6.so',
      'libHSbytestring-0.11.5.3-ghc9.6.6.so',
      'libHScontainers-0.6.7-ghc9.6.6.so',
      'libHSdeepseq-1.4.8.1-ghc9.6.6.so',
      'libHSdirectory-1.3.8.5-ghc9.6.6.so',
      'libHSexceptions-0.10.7-ghc9.6.6.so',
      'libHSfilepath-1.4.300.1-ghc9.6.6.so',
      'libHSghc-bignum-1.3-ghc9.6.6.so',
      'libHSghc-boot-9.6.6-ghc9.6.6.so',
      'libHSghc-boot-th-9.6.6-ghc9.6.6.so',
      'libHSghc-heap-9.6.6-ghc9.6.6.so',
      'libHSghc-prim-0.10.0-ghc9.6.6.so',
      'libHSghci-9.6.6-ghc9.6.6.so',
      'libHSinteger-gmp-1.1-ghc9.6.6.so',
      'libHSmtl-2.3.1-ghc9.6.6.so',
      'libHSparsec-3.1.16.1-ghc9.6.6.so',
      'libHSpretty-1.1.3.6-ghc9.6.6.so',
      'libHSprocess-1.6.19.0-ghc9.6.6.so',
      'libHSrts-1.0.2-ghc9.6.6.so',
      'libHSstm-2.5.1.0-ghc9.6.6.so',
      'libHStemplate-haskell-2.20.0.0-ghc9.6.6.so',
      'libHSterminfo-0.4.1.6-ghc9.6.6.so',
      'libHStext-2.0.2-ghc9.6.6.so',
      'libHStime-1.12.2-ghc9.6.6.so',
      'libHStransformers-0.6.1.0-ghc9.6.6.so',
      'libHSunix-2.8.4.0-ghc9.6.6.so',
      'libHSxhtml-3000.2.2.1-ghc9.6.6.so',
    ],
    neededSonames: [
      'ld-linux-x86-64.so.2',
      'libHSCabal-3.10.3.0-ghc9.6.6.so',
      'libHSCabal-syntax-3.10.3.0-ghc9.6.6.so',
      'libHSarray-0.5.6.0-ghc9.6.6.so',
      'libHSbase-4.18.2.1-ghc9.6.6.so',
      'libHSbinary-0.8.9.1-ghc9.6.6.so',
      'libHSbytestring-0.11.5.3-ghc9.6.6.so',
      'libHScontainers-0.6.7-ghc9.6.6.so',
      'libHSdeepseq-1.4.8.1-ghc9.6.6.so',
      'libHSdirectory-1.3.8.5-ghc9.6.6.so',
      'libHSexceptions-0.10.7-ghc9.6.6.so',
      'libHSfilepath-1.4.300.1-ghc9.6.6.so',
      'libHSghc-bignum-1.3-ghc9.6.6.so',
      'libHSghc-boot-9.6.6-ghc9.6.6.so',
      'libHSghc-boot-th-9.6.6-ghc9.6.6.so',
      'libHSghc-heap-9.6.6-ghc9.6.6.so',
      'libHSghc-prim-0.10.0-ghc9.6.6.so',
      'libHSghci-9.6.6-ghc9.6.6.so',
      'libHSinteger-gmp-1.1-ghc9.6.6.so',
      'libHSmtl-2.3.1-ghc9.6.6.so',
      'libHSparsec-3.1.16.1-ghc9.6.6.so',
      'libHSpretty-1.1.3.6-ghc9.6.6.so',
      'libHSprocess-1.6.19.0-ghc9.6.6.so',
      'libHSrts-1.0.2-ghc9.6.6.so',
      'libHSstm-2.5.1.0-ghc9.6.6.so',
      'libHStemplate-haskell-2.20.0.0-ghc9.6.6.so',
      'libHSterminfo-0.4.1.6-ghc9.6.6.so',
      'libHStext-2.0.2-ghc9.6.6.so',
      'libHStime-1.12.2-ghc9.6.6.so',
      'libHStransformers-0.6.1.0-ghc9.6.6.so',
      'libHSunix-2.8.4.0-ghc9.6.6.so',
      'libc.so.6',
      'libffi.so.8',
      'libgmp.so.10',
      'libm.so.6',
      'libncursesw.so.6',
      'libnuma.so.1',
    ],
  },
  {
    pkgname: 'gmp',
    version: '6.3.0',
    providedSonames: ['libgmp.so.10', 'libgmpxx.so.4'],
    neededSonames: ['libc.so.6', 'libgcc_s.so.1', 'libgmp.so.10', 'libstdc++.so.6'],
  },
  {
    pkgname: 'haskell-old-locale',
    version: '1.0.0.7',
    providedSonames: ['libHSold-locale-1.0.0.7-Gunit3UBy5P9OGDVFY5MhC-ghc9.6.6.so'],
    neededSonames: [
      'libHSbase-4.18.2.1-ghc9.6.6.so',
      'libHSghc-bignum-1.3-ghc9.6.6.so',
      'libHSghc-prim-0.10.0-ghc9.6.6.so',
      'libc.so.6',
      'libgmp.so.10',
      'libm.so.6',
    ],
  },
  {
    pkgname: 'haskell-old-time',
    version: '1.1.1.0',
    providedSonames: ['libHSold-time-1.1.1.0-9WWjmNUa02UkaP5dbkbXm-ghc9.6.6.so'],
    neededSonames: [
      'libHSbase-4.18.2.1-ghc9.6.6.so',
      'libHSghc-bignum-1.3-ghc9.6.6.so',
      'libHSghc-prim-0.10.0-ghc9.6.6.so',
      'libHSold-locale-1.0.0.7-Gunit3UBy5P9OGDVFY5MhC-ghc9.6.6.so',
      'libc.so.6',
      'libgmp.so.10',
      'libm.so.6',
    ],
  },
  {
    pkgname: 'haskell-regex-base',
    version: '0.94.0.3',
    providedSonames: ['libHSregex-base-0.94.0.3-6fVrfocUW2t4u08iX8Rj6b-ghc9.6.6.so'],
    neededSonames: [
      'libHSarray-0.5.6.0-ghc9.6.6.so',
      'libHSbase-4.18.2.1-ghc9.6.6.so',
      'libHSbinary-0.8.9.1-ghc9.6.6.so',
      'libHSbytestring-0.11.5.3-ghc9.6.6.so',
      'libHScontainers-0.6.7-ghc9.6.6.so',
      'libHSdeepseq-1.4.8.1-ghc9.6.6.so',
      'libHSghc-bignum-1.3-ghc9.6.6.so',
      'libHSghc-boot-th-9.6.6-ghc9.6.6.so',
      'libHSghc-prim-0.10.0-ghc9.6.6.so',
      'libHSpretty-1.1.3.6-ghc9.6.6.so',
      'libHStemplate-haskell-2.20.0.0-ghc9.6.6.so',
      'libHStext-2.0.2-ghc9.6.6.so',
      'libc.so.6',
      'libgmp.so.10',
      'libm.so.6',
    ],
  },
  {
    pkgname: 'haskell-regex-compat',
    version: '0.95.2.2',
    providedSonames: ['libHSregex-compat-0.95.2.2-DwcD5qxZGc67j8Pwq49pag-ghc9.6.6.so'],
    neededSonames: [
      'libHSarray-0.5.6.0-ghc9.6.6.so',
      'libHSbase-4.18.2.1-ghc9.6.6.so',
      'libHSbinary-0.8.9.1-ghc9.6.6.so',
      'libHSbytestring-0.11.5.3-ghc9.6.6.so',
      'libHScontainers-0.6.7-ghc9.6.6.so',
      'libHSdeepseq-1.4.8.1-ghc9.6.6.so',
      'libHSghc-bignum-1.3-ghc9.6.6.so',
      'libHSghc-boot-th-9.6.6-ghc9.6.6.so',
      'libHSghc-prim-0.10.0-ghc9.6.6.so',
      'libHSpretty-1.1.3.6-ghc9.6.6.so',
      'libHSregex-base-0.94.0.3-6fVrfocUW2t4u08iX8Rj6b-ghc9.6.6.so',
      'libHSregex-posix-0.96.0.2-LsCmj8tXKerCmkZ6TKO5qF-ghc9.6.6.so',
      'libHStemplate-haskell-2.20.0.0-ghc9.6.6.so',
      'libHStext-2.0.2-ghc9.6.6.so',
      'libc.so.6',
      'libgmp.so.10',
      'libm.so.6',
    ],
  },
  {
    pkgname: 'haskell-regex-posix',
    version: '0.96.0.2',
    providedSonames: ['libHSregex-posix-0.96.0.2-LsCmj8tXKerCmkZ6TKO5qF-ghc9.6.6.so'],
    neededSonames: [
      'libHSarray-0.5.6.0-ghc9.6.6.so',
      'libHSbase-4.18.2.1-ghc9.6.6.so',
      'libHSbinary-0.8.9.1-ghc9.6.6.so',
      'libHSbytestring-0.11.5.3-ghc9.6.6.so',
      'libHScontainers-0.6.7-ghc9.6.6.so',
      'libHSdeepseq-1.4.8.1-ghc9.6.6.so',
      'libHSghc-bignum-1.3-ghc9.6.6.so',
      'libHSghc-boot-th-9.6.6-ghc9.6.6.so',
      'libHSghc-prim-0.10.0-ghc9.6.6.so',
      'libHSpretty-1.1.3.6-ghc9.6.6.so',
      'libHSregex-base-0.94.0.3-6fVrfocUW2t4u08iX8Rj6b-ghc9.6.6.so',
      'libHStemplate-haskell-2.20.0.0-ghc9.6.6.so',
      'libHStext-2.0.2-ghc9.6.6.so',
      'libc.so.6',
      'libgmp.so.10',
      'libm.so.6',
    ],
  },
  {
    pkgname: 'haskell-split',
    version: '0.2.5',
    providedSonames: ['libHSsplit-0.2.5-3KQHz3VjCt4O3lCLzOFzl-ghc9.6.6.so'],
    neededSonames: [
      'libHSbase-4.18.2.1-ghc9.6.6.so',
      'libHSghc-bignum-1.3-ghc9.6.6.so',
      'libHSghc-prim-0.10.0-ghc9.6.6.so',
      'libc.so.6',
      'libgmp.so.10',
      'libm.so.6',
    ],
  },
  {
    pkgname: 'haskell-syb',
    version: '0.7.4',
    providedSonames: ['libHSsyb-0.7.4-CWkOfF6Y0mt62kPybHOEB1-ghc9.6.6.so'],
    neededSonames: [
      'libHSbase-4.18.2.1-ghc9.6.6.so',
      'libHSghc-bignum-1.3-ghc9.6.6.so',
      'libHSghc-prim-0.10.0-ghc9.6.6.so',
      'libc.so.6',
      'libgmp.so.10',
      'libm.so.6',
    ],
  },
  {
    pkgname: 'libffi',
    version: '3.8.0',
    providedSonames: ['libffi.so.8'],
    neededSonames: ['libc.so.6'],
  },
  {
    pkgname: 'numactl',
    version: '2.0.19',
    providedSonames: ['libnuma.so.1'],
    neededSonames: ['ld-linux-x86-64.so.2', 'libc.so.6', 'libnuma.so.1'],
  },
  {
    pkgname: 'mujs',
    version: '1.3.9',
    providedSonames: ['libmujs.so'],
    neededSonames: ['libc.so.6', 'libm.so.6'],
  },
  {
    pkgname: 'r',
    version: '4.6.1',
    providedSonames: [
      'KernSmooth.so',
      'MASS.so',
      'Matrix.so',
      'R_X11.so',
      'R_de.so',
      'cairo.so',
      'class.so',
      'cluster.so',
      'foreign.so',
      'grDevices.so',
      'graphics.so',
      'grid.so',
      'internet.so',
      'lapack.so',
      'lattice.so',
      'libR.so',
      'libRmath.so',
      'methods.so',
      'mgcv.so',
      'nlme.so',
      'nnet.so',
      'parallel.so',
      'rpart.so',
      'spatial.so',
      'splines.so',
      'stats.so',
      'survival.so',
      'tcltk.so',
      'utils.so',
      'utils.so',
    ],
    neededSonames: [
      'ld-linux-x86-64.so.2',
      'libR.so',
      'libX11.so.6',
      'libXmu.so.6',
      'libXt.so.6',
      'libblas.so.3',
      'libbz2.so.1.0',
      'libc.so.6',
      'libcairo.so.2',
      'libcurl.so.4',
      'libdeflate.so.0',
      'libgcc_s.so.1',
      'libgobject-2.0.so.0',
      'libgomp.so.1',
      'libicui18n.so.78',
      'libicuuc.so.78',
      'libjpeg.so.8',
      'liblapack.so.3',
      'liblzma.so.5',
      'libm.so.6',
      'libpango-1.0.so.0',
      'libpangocairo-1.0.so.0',
      'libpcre2-8.so.0',
      'libpng16.so.16',
      'libreadline.so.8',
      'libtcl8.6.so',
      'libtiff.so.6',
      'libtirpc.so.3',
      'libtk8.6.so',
      'libz.so.1',
      'libzstd.so.1',
    ],
  },
  {
    pkgname: 'tcl',
    version: '8.6.16',
    providedSonames: [
      'libitcl4.3.2.so',
      'libtcl.so',
      'libtcl8.6.so',
      'libtdbc1.1.10.so',
      'libtdbcmysql1.1.10.so',
      'libtdbcodbc1.1.10.so',
      'libtdbcpostgres1.1.10.so',
      'libthread2.8.11.so',
    ],
    neededSonames: ['libc.so.6', 'libm.so.6', 'libz.so.1'],
  },
  {
    pkgname: 'tk',
    version: '8.6.16',
    providedSonames: ['libtk.so', 'libtk8.6.so'],
    neededSonames: ['libX11.so.6', 'libXft.so.2', 'libXss.so.1', 'libc.so.6', 'libfontconfig.so.1', 'libm.so.6'],
  },
  {
    pkgname: 'xorg-server',
    version: '21.1.24',
    providedSonames: [
      'inputtest_drv.so',
      'libexa.so',
      'libfbdevhw.so',
      'libglamoregl.so',
      'libglx.so',
      'libint10.so',
      'libshadow.so',
      'libshadowfb.so',
      'libvgahw.so',
      'libwfb.so',
      'modesetting_drv.so',
    ],
    neededSonames: [
      'libGL.so.1',
      'libXau.so.6',
      'libXdmcp.so.6',
      'libXfont2.so.2',
      'libc.so.6',
      'libdbus-1.so.3',
      'libdrm.so.2',
      'libepoxy.so.0',
      'libgbm.so.1',
      'libm.so.6',
      'libnettle.so.9',
      'libpciaccess.so.0',
      'libpixman-1.so.0',
      'libsystemd.so.0',
      'libtirpc.so.3',
      'libudev.so.1',
      'libunwind.so.8',
      'libxcvt.so.0',
      'libxshmfence.so.1',
    ],
  },
  {
    pkgname: 'qt6-base',
    version: '6.11.1',
    providedSonames: [
      'libQt6Concurrent.so.6',
      'libQt6Core.so.6',
      'libQt6DBus.so.6',
      'libQt6EglFSDeviceIntegration.so.6',
      'libQt6EglFsKmsGbmSupport.so.6',
      'libQt6EglFsKmsSupport.so.6',
      'libQt6Gui.so.6',
      'libQt6Network.so.6',
      'libQt6OpenGL.so.6',
      'libQt6OpenGLWidgets.so.6',
      'libQt6PrintSupport.so.6',
      'libQt6Sql.so.6',
      'libQt6Test.so.6',
      'libQt6WaylandClient.so.6',
      'libQt6Widgets.so.6',
      'libQt6WlShellIntegration.so.6',
      'libQt6XcbQpa.so.6',
      'libQt6Xml.so.6',
    ],
    neededSonames: [
      'ld-linux-x86-64.so.2',
      'libEGL.so.1',
      'libGLX.so.0',
      'libICE.so.6',
      'libOpenGL.so.0',
      'libQt6Core.so.6',
      'libQt6DBus.so.6',
      'libQt6EglFSDeviceIntegration.so.6',
      'libQt6EglFsKmsGbmSupport.so.6',
      'libQt6EglFsKmsSupport.so.6',
      'libQt6Gui.so.6',
      'libQt6Network.so.6',
      'libQt6OpenGL.so.6',
      'libQt6PrintSupport.so.6',
      'libQt6Sql.so.6',
      'libQt6WaylandClient.so.6',
      'libQt6Widgets.so.6',
      'libQt6WlShellIntegration.so.6',
      'libQt6XcbQpa.so.6',
      'libSM.so.6',
      'libX11-xcb.so.1',
      'libX11.so.6',
      'libb2.so.1',
      'libbrotlidec.so.1',
      'libc.so.6',
      'libcrypto.so.3',
      'libcups.so.2',
      'libdbus-1.so.3',
      'libdouble-conversion.so.3',
      'libdrm.so.2',
      'libfbclient.so.2',
      'libfontconfig.so.1',
      'libfreetype.so.6',
      'libgbm.so.1',
      'libgcc_s.so.1',
      'libgdk-3.so.0',
      'libgdk_pixbuf-2.0.so.0',
      'libgio-2.0.so.0',
      'libglib-2.0.so.0',
      'libgobject-2.0.so.0',
      'libgssapi_krb5.so.2',
      'libgtk-3.so.0',
      'libharfbuzz.so.0',
      'libicui18n.so.78',
      'libicuuc.so.78',
      'libinput.so.10',
      'libjpeg.so.8',
      'libm.so.6',
      'libmariadb.so.3',
      'libmd4c.so.0',
      'libmtdev.so.1',
      'libodbc.so.2',
      'libpango-1.0.so.0',
      'libpcre2-16.so.0',
      'libpng16.so.16',
      'libpq.so.5',
      'libproxy.so.1',
      'libsqlite3.so.0',
      'libssl.so.3',
      'libstdc++.so.6',
      'libsystemd.so.0',
      'libts.so.0',
      'libudev.so.1',
      'liburing.so.2',
      'libwayland-client.so.0',
      'libwayland-cursor.so.0',
      'libwayland-egl.so.1',
      'libxcb-cursor.so.0',
      'libxcb-glx.so.0',
      'libxcb-icccm.so.4',
      'libxcb-image.so.0',
      'libxcb-keysyms.so.1',
      'libxcb-randr.so.0',
      'libxcb-render-util.so.0',
      'libxcb-render.so.0',
      'libxcb-shape.so.0',
      'libxcb-shm.so.0',
      'libxcb-sync.so.1',
      'libxcb-xfixes.so.0',
      'libxcb-xinput.so.0',
      'libxcb-xkb.so.1',
      'libxcb.so.1',
      'libxkbcommon-x11.so.0',
      'libxkbcommon.so.0',
      'libz.so.1',
      'libzstd.so.1',
    ],
  },
  {
    pkgname: 'libxcb',
    version: '1.17.0',
    providedSonames: [
      'libxcb-composite.so.0',
      'libxcb-damage.so.0',
      'libxcb-dbe.so.0',
      'libxcb-dpms.so.0',
      'libxcb-dri2.so.0',
      'libxcb-dri3.so.0',
      'libxcb-glx.so.0',
      'libxcb-present.so.0',
      'libxcb-randr.so.0',
      'libxcb-record.so.0',
      'libxcb-render.so.0',
      'libxcb-res.so.0',
      'libxcb-screensaver.so.0',
      'libxcb-shape.so.0',
      'libxcb-shm.so.0',
      'libxcb-sync.so.1',
      'libxcb-xf86dri.so.0',
      'libxcb-xfixes.so.0',
      'libxcb-xinerama.so.0',
      'libxcb-xinput.so.0',
      'libxcb-xkb.so.1',
      'libxcb-xtest.so.0',
      'libxcb-xv.so.0',
      'libxcb-xvmc.so.0',
      'libxcb.so.1',
    ],
    neededSonames: ['libXau.so.6', 'libXdmcp.so.6', 'libc.so.6', 'libxcb.so.1'],
  },
  {
    pkgname: 'libepoxy',
    version: '1.5.10',
    providedSonames: ['libepoxy.so.0'],
    neededSonames: ['libc.so.6'],
  },
  {
    pkgname: 'kconfig',
    version: '6.28.0',
    providedSonames: ['libKF6ConfigCore.so.6', 'libKF6ConfigGui.so.6', 'libKF6ConfigQml.so.6'],
    neededSonames: [
      'libKF6ConfigCore.so.6',
      'libKF6ConfigGui.so.6',
      'libKF6ConfigQml.so.6',
      'libQt6Core.so.6',
      'libQt6DBus.so.6',
      'libQt6Gui.so.6',
      'libQt6Qml.so.6',
      'libQt6Quick.so.6',
      'libQt6Xml.so.6',
      'libc.so.6',
      'libm.so.6',
      'libstdc++.so.6',
    ],
  },
  {
    pkgname: 'kcoreaddons',
    version: '6.28.0',
    providedSonames: ['KCoreAddons.cpython-314-x86_64-linux-gnu.so', 'libKF6CoreAddons.so.6'],
    neededSonames: [
      'libKF6CoreAddons.so.6',
      'libQt6Core.so.6',
      'libQt6DBus.so.6',
      'libQt6Network.so.6',
      'libQt6Qml.so.6',
      'libc.so.6',
      'libgcc_s.so.1',
      'libm.so.6',
      'libmount.so.1',
      'libpyside6.cpython-314-x86_64-linux-gnu.so.6.11',
      'libpython3.14.so.1.0',
      'libshiboken6.cpython-314-x86_64-linux-gnu.so.6.11',
      'libstdc++.so.6',
      'libudev.so.1',
    ],
  },
  {
    pkgname: 'ki18n',
    version: '6.28.0',
    providedSonames: ['libKF6I18n.so.6', 'libKF6I18nLocaleData.so.6', 'libKF6I18nQml.so.6'],
    neededSonames: [
      'libKF6I18n.so.6',
      'libKF6I18nLocaleData.so.6',
      'libKF6I18nQml.so.6',
      'libQt6Core.so.6',
      'libQt6Qml.so.6',
      'libc.so.6',
      'libstdc++.so.6',
    ],
  },
  {
    pkgname: 'kcmutils',
    version: '6.28.0',
    providedSonames: ['libKF6KCMUtils.so.6', 'libKF6KCMUtilsCore.so.6', 'libKF6KCMUtilsQuick.so.6'],
    neededSonames: [
      'libKF6ConfigCore.so.6',
      'libKF6ConfigWidgets.so.6',
      'libKF6CoreAddons.so.6',
      'libKF6GuiAddons.so.6',
      'libKF6I18n.so.6',
      'libKF6I18nQml.so.6',
      'libKF6ItemViews.so.6',
      'libKF6KCMUtils.so.6',
      'libKF6KCMUtilsCore.so.6',
      'libKF6KCMUtilsQuick.so.6',
      'libKF6KIOGui.so.6',
      'libKF6Service.so.6',
      'libKF6WidgetsAddons.so.6',
      'libKF6XmlGui.so.6',
      'libQt6Core.so.6',
      'libQt6DBus.so.6',
      'libQt6Gui.so.6',
      'libQt6Qml.so.6',
      'libQt6Quick.so.6',
      'libQt6QuickWidgets.so.6',
      'libQt6Widgets.so.6',
      'libc.so.6',
      'libstdc++.so.6',
    ],
  },
  {
    pkgname: 'kwidgetsaddons',
    version: '6.28.0',
    providedSonames: ['KWidgetsAddons.cpython-314-x86_64-linux-gnu.so', 'libKF6WidgetsAddons.so.6'],
    neededSonames: [
      'libKF6WidgetsAddons.so.6',
      'libQt6Core.so.6',
      'libQt6Gui.so.6',
      'libQt6Widgets.so.6',
      'libc.so.6',
      'libpyside6.cpython-314-x86_64-linux-gnu.so.6.11',
      'libpython3.14.so.1.0',
      'libshiboken6.cpython-314-x86_64-linux-gnu.so.6.11',
      'libstdc++.so.6',
    ],
  },
  {
    pkgname: 'kdecoration',
    version: '6.7.4',
    providedSonames: ['libkdecorations3.so.6', 'libkdecorations3private.so.2'],
    neededSonames: [
      'libKF6I18n.so.6',
      'libQt6Core.so.6',
      'libQt6Gui.so.6',
      'libc.so.6',
      'libkdecorations3private.so.2',
      'libstdc++.so.6',
    ],
  },
  {
    pkgname: 'kwin',
    version: '6.7.4',
    providedSonames: ['libkcmkwincommon.so.6', 'libkwin.so.6'],
    neededSonames: [
      'ld-linux-x86-64.so.2',
      'libKF6AuthCore.so.6',
      'libKF6ColorScheme.so.6',
      'libKF6ConfigCore.so.6',
      'libKF6ConfigGui.so.6',
      'libKF6ConfigQml.so.6',
      'libKF6CoreAddons.so.6',
      'libKF6Crash.so.6',
      'libKF6DBusAddons.so.6',
      'libKF6GlobalAccel.so.6',
      'libKF6GuiAddons.so.6',
      'libKF6I18n.so.6',
      'libKF6I18nQml.so.6',
      'libKF6IdleTime.so.6',
      'libKF6KCMUtils.so.6',
      'libKF6KCMUtilsCore.so.6',
      'libKF6KCMUtilsQuick.so.6',
      'libKF6NewStuffCore.so.6',
      'libKF6NewStuffWidgets.so.6',
      'libKF6Notifications.so.6',
      'libKF6Package.so.6',
      'libKF6Service.so.6',
      'libKF6Svg.so.6',
      'libKF6WidgetsAddons.so.6',
      'libKF6WindowSystem.so.6',
      'libKF6XmlGui.so.6',
      'libKGlobalAccelD.so.0',
      'libKNightTime.so.0',
      'libKScreenLocker.so.6',
      'libKWaylandClient.so.6',
      'libPlasmaActivities.so.7',
      'libQt6Core.so.6',
      'libQt6DBus.so.6',
      'libQt6Gui.so.6',
      'libQt6OpenGL.so.6',
      'libQt6Qml.so.6',
      'libQt6Quick.so.6',
      'libQt6Svg.so.6',
      'libQt6UiTools.so.6',
      'libQt6Widgets.so.6',
      'libc.so.6',
      'libcanberra.so.0',
      'libdisplay-info.so.3',
      'libdrm.so.2',
      'libeis.so.1',
      'libepoxy.so.0',
      'libevdev.so.2',
      'libgbm.so.1',
      'libgcc_s.so.1',
      'libinput.so.10',
      'libkcmkwincommon.so.6',
      'libkdecorations3.so.6',
      'libkdecorations3private.so.2',
      'libkwin.so.6',
      'liblcms2.so.2',
      'libm.so.6',
      'libpipewire-0.3.so.0',
      'libqaccessibilityclient-qt6.so.0',
      'libstdc++.so.6',
      'libsystemd.so.0',
      'libudev.so.1',
      'libvulkan.so.1',
      'libwayland-client.so.0',
      'libwayland-server.so.0',
      'libxcb-composite.so.0',
      'libxcb-dri3.so.0',
      'libxcb-icccm.so.4',
      'libxcb-keysyms.so.1',
      'libxcb-present.so.0',
      'libxcb-randr.so.0',
      'libxcb-render.so.0',
      'libxcb-res.so.0',
      'libxcb-shape.so.0',
      'libxcb-shm.so.0',
      'libxcb-sync.so.1',
      'libxcb-xfixes.so.0',
      'libxcb-xinput.so.0',
      'libxcb.so.1',
      'libxcvt.so.0',
      'libxkbcommon.so.0',
    ],
  },
];

/** Total distinct provided sonames across all real providers (must be >= MIN_PROVIDED_SONAMES). */
export const REAL_PROVIDED_SONAME_COUNT = REAL_ARCH_PROVIDERS.reduce(
  (acc, p) => acc + new Set(p.providedSonames).size,
  0,
);

/**
 * Real-world Chaotic consumers captured from the live DB. Their needed sonames
 * are genuine: scid links libtcl8.6.so (a no-SONAME lib tcl now provides),
 * xorgxrdp-glamor links libglamoregl.so (xorg-server), and tio links
 * liblua.so.5.4 which lua 5.5.1 no longer ships (a genuine ABI break).
 */
export const REAL_CHAOTIC_CONSUMERS: RealPkgSeed[] = [
  {
    pkgname: 'scid',
    version: '4.7.4',
    neededSonames: ['libc.so.6', 'libgcc_s.so.1', 'libm.so.6', 'libstdc++.so.6', 'libtcl8.6.so'],
    providedSonames: [],
  },
  {
    pkgname: 'xorgxrdp-glamor',
    version: '0.1.0',
    neededSonames: ['libc.so.6', 'libglamoregl.so'],
    providedSonames: [],
  },
  {
    pkgname: 'tio',
    version: '3.9',
    neededSonames: ['libc.so.6', 'libglib-2.0.so.0', 'liblua.so.5.4'],
    providedSonames: [],
  },
  {
    pkgname: 'bluespec-git',
    version: 'r1127.941eecfe',
    neededSonames: [
      'libHSarray-0.5.6.0-ghc9.6.6.so',
      'libHSbase-4.18.2.1-ghc9.6.6.so',
      'libHSbinary-0.8.9.1-ghc9.6.6.so',
      'libHSbytestring-0.11.5.3-ghc9.6.6.so',
      'libHScontainers-0.6.7-ghc9.6.6.so',
      'libHSdeepseq-1.4.8.1-ghc9.6.6.so',
      'libHSdirectory-1.3.8.5-ghc9.6.6.so',
      'libHSexceptions-0.10.7-ghc9.6.6.so',
      'libHSfilepath-1.4.300.1-ghc9.6.6.so',
      'libHSghc-bignum-1.3-ghc9.6.6.so',
      'libHSghc-boot-th-9.6.6-ghc9.6.6.so',
      'libHSghc-prim-0.10.0-ghc9.6.6.so',
      'libHSinteger-gmp-1.1-ghc9.6.6.so',
      'libHSmtl-2.3.1-ghc9.6.6.so',
      'libHSold-locale-1.0.0.7-Gunit3UBy5P9OGDVFY5MhC-ghc9.6.6.so',
      'libHSold-time-1.1.1.0-9WWjmNUa02UkaP5dbkbXm-ghc9.6.6.so',
      'libHSpretty-1.1.3.6-ghc9.6.6.so',
      'libHSprocess-1.6.19.0-ghc9.6.6.so',
      'libHSregex-base-0.94.0.3-6fVrfocUW2t4u08iX8Rj6b-ghc9.6.6.so',
      'libHSregex-compat-0.95.2.2-DwcD5qxZGc67j8Pwq49pag-ghc9.6.6.so',
      'libHSregex-posix-0.96.0.2-LsCmj8tXKerCmkZ6TKO5qF-ghc9.6.6.so',
      'libHSrts-1.0.2-ghc9.6.6.so',
      'libHSsplit-0.2.5-3KQHz3VjCt4O3lCLzOFzl-ghc9.6.6.so',
      'libHSstm-2.5.1.0-ghc9.6.6.so',
      'libHSstrict-concurrency-0.2.4.3-tAwULt7um46FGRQhsBra7-ghc9.6.6.so',
      'libHSsyb-0.7.4-CWkOfF6Y0mt62kPybHOEB1-ghc9.6.6.so',
      'libHStemplate-haskell-2.20.0.0-ghc9.6.6.so',
      'libHStext-2.0.2-ghc9.6.6.so',
      'libHStime-1.12.2-ghc9.6.6.so',
      'libHStransformers-0.6.1.0-ghc9.6.6.so',
      'libHSunix-2.8.4.0-ghc9.6.6.so',
      'libc.so.6',
      'libffi.so.8',
      'libgcc_s.so.1',
      'libgmp.so.10',
      'libm.so.6',
      'libnuma.so.1',
      'libstdc++.so.6',
      'libstp.so.1',
      'libtcl8.6.so',
      'libyices.so.2.6',
    ],
    providedSonames: ['libbdpi.so', 'libstp.so.1', 'libyices.so.2.6'],
  },
  {
    pkgname: 'kwin-effects-better-blur-dx',
    version: '2.5.1',
    neededSonames: [
      'libKF6ConfigCore.so.6',
      'libKF6ConfigGui.so.6',
      'libKF6CoreAddons.so.6',
      'libKF6I18n.so.6',
      'libKF6KCMUtils.so.6',
      'libKF6WidgetsAddons.so.6',
      'libQt6Core.so.6',
      'libQt6DBus.so.6',
      'libQt6Gui.so.6',
      'libQt6Widgets.so.6',
      'libc.so.6',
      'libepoxy.so.0',
      'libkdecorations3.so.6',
      'libkwin.so.6',
      'libm.so.6',
      'libstdc++.so.6',
      'libxcb.so.1',
    ],
    providedSonames: [],
  },
];

/**
 * Real-world Chaotic providers (packages that both link against and ship
 * libraries). haskell-strict-concurrency is a Chaotic package providing
 * libHSstrict-concurrency for bluespec-git.
 */
export const REAL_CHAOTIC_PROVIDERS: RealPkgSeed[] = [
  {
    pkgname: 'haskell-strict-concurrency',
    version: '0.2.4.3',
    neededSonames: [
      'libHSarray-0.5.6.0-ghc9.6.6.so',
      'libHSbase-4.18.2.1-ghc9.6.6.so',
      'libHSdeepseq-1.4.8.1-ghc9.6.6.so',
      'libHSghc-bignum-1.3-ghc9.6.6.so',
      'libHSghc-prim-0.10.0-ghc9.6.6.so',
      'libc.so.6',
      'libgmp.so.10',
      'libm.so.6',
    ],
    providedSonames: ['libHSstrict-concurrency-0.2.4.3-tAwULt7um46FGRQhsBra7-ghc9.6.6.so'],
  },
];
